### ISSUE TITLE
request.POST is accessed in `CSRFCryptMiddleware`

### ISSUE THREAD

**Issue by davepeck** [lpomfrey/django-debreach#11]
The [Django docs](https://docs.djangoproject.com/en/1.7/topics/http/middleware/#process-view) say that accessing `request.POST` (or `request.REQUEST`) in middleware should _usually_ be avoided, since it prevents views running after the middleware from being able to modify the upload handlers for the request.

The one exception appears to be Django's own `CsrfViewMiddleware`, since `csrf_exempt()` and `csrf_protect()` let you have explicit control.

One approach in `django-debreach` might be to move from implementing `process_request(...)` to `process_view(self, request, view, ...)` and -- like Django's own CSRF middleware does -- to explicitly test the `view.csrf_exempt` flag and bail out if it's `True`.

Thanks for the useful library!

**Comment by lpomfrey** [comment]
Good point, we probably should do something similar. Although this would potentially break backwards compatibility, I can't imagine that many cases where it would cause issues.

If you wanted to submit a pull request let me know, overwise I'll take it on when I get 5 minutes.
