### ISSUE TITLE
debreach vs. base django

### ISSUE THREAD

**Issue by pombredanne** [lpomfrey/django-debreach#13]
What's you take on the upcoming https://code.djangoproject.com/ticket/20869 ?
Thanks!

**Comment by lpomfrey** [comment]
The implementation looks sound, as one would expect. It's good to see an fix make it into core finally.

I notice they're not doing anything regarding content length though, so I guess django-debreach may be of some minor use if you wanted to use that for a bit of extra protection.

**Comment by pombredanne** [comment]
@lpomfrey Thanks! I was surprised your code was not used there. May be you could contribute?
