### ISSUE TITLE
django-debreach does not work with Django 3

### ISSUE THREAD

**Issue by javierpena** [lpomfrey/django-debreach#17]
Hi,

The Fedora project is updating the Django package to Django 3, and it looks like there is an incompatibility between django-debrach and the new version [1]. I am not sure if the issue is isolated to the usage of django.utils.six, or there is more to it.

Could you check this out? Thanks!

[1] - https://bugzilla.redhat.com/show_bug.cgi?id=1759926

**Comment by lpomfrey** [comment]
Sure, I'll take a look over the next couple of days and get a release out.

Thanks.

**Comment by lpomfrey** [comment]
This should be fixed in 2.0.0 which drops support for django < 2.0 and python 2.7 completely. Let me know if you have any issues.

Thanks. :)

**Comment by javierpena** [comment]
That was fast! Thanks a lot.

Would it be possible to upload a tarball to PyPi, too? We need that to build the package, the wheel does not work for us.

**Comment by lpomfrey** [comment]
Oops, I thought I had already, sorry. Should be there now.

**Comment by javierpena** [comment]
Awesome :). Now I'm still finding some troubles while running unit tests:

======================================================================
ERROR: debreach.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: debreach.tests
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/tmp/django-debreach/debreach/tests.py", line 11, in <module>
    from debreach.decorators import append_random_comment, random_comment_exempt
  File "/tmp/django-debreach/debreach/decorators.py", line 4, in <module>
    from django.utils.decorators import available_attrs, decorator_from_middleware
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/tmp/django-debreach/.eggs/Django-3.0a1-py3.7.egg/django/utils/decorators.py)

Do you think this is also related to Django 3?

**Comment by javierpena** [comment]
Yes, 2.0.1 works like a charm. Thanks again!
