### ISSUE TITLE
Violates SEO Cloaking

### ISSUE THREAD

**Issue by 9mido** [lpomfrey/django-debreach#19]
Because a randomly inserted comment at the end of the HTML varies in byte size for each page load, the number of bytes of each page load changes every time. Googlebot sees that there is a change in number of bytes which is different than what the user might see at a given point in time. Cloaking is considered a very bad black hat SEO technique that Google will punish your website for. 

https://www.webtoolhub.com/tn561346-cloaking-checker.aspx

Removing the django-debreach library resolved the cloaking issue and the website is no longer considered violating cloaking. 

But other cloaking checker links online indicate that with the django-debreach library installed, no cloaking is found.

**Comment by lpomfrey** [comment]
Given that the whole function of the library is changing the content length to counteract the BREACH security issue, and the goal here is security and not SEO optimisation, I can't really see that this is a bug. Unless you have any suggestions of a feature to add to make it possible to add random length data to a page without causing search engines to complain about this (which given the function of the library and the nature of said SEO problem I can't immediately see is possible) I'm going to close this.

That said, it's a random comment, not any meaningful content, so I should imagine if Google had any sense they would ignore it.
