### ISSUE TITLE
Is debreach still needed?

### ISSUE THREAD

**Issue by guettli** [lpomfrey/django-debreach#20]
> In order to protect against BREACH attacks, the token is not simply the secret; a random mask is prepended to the secret and used to scramble it.

https://docs.djangoproject.com/en/3.2/ref/csrf/#how-it-works

Is django-debreach still needed?

**Comment by lpomfrey** [comment]
From the README:

> django-debreach provides additional protection to Django's built in CSRF token masking by randomising the content length of each response. This is achieved by adding a random string of between 12 and 25 characters as a comment to the end of the HTML content.

So if you want a belt and braces approach it may be worth using it. Initially django-debreach offered both of these mitigations before django itself implemented the token masking.

**Comment by guettli** [comment]
Thank you for the historical information. I was not aware of this. At least for my current context a belt and braces approach makes no sense. Thank you.
