### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by jayvdb** [lpomfrey/django-debreach#21]
It would be worth adding a note on the README explaining https://github.com/lpomfrey/django-debreach/issues/20 , and also adding info regarding Django 4.

If there is still benefit in using this plugin with Django 4, there are some new incompatibilities in the tests at least.

```py
[   60s]   File "/home/abuild/rpmbuild/BUILD/django-debreach-2.0.1/test_project/urls.py", line 4, in <module>
[   60s]     from django.conf.urls import url
[   60s] ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/lib/python3.9/site-packages/django/conf/urls/__init__.py)
```

```py
[   42s]   File "/home/abuild/rpmbuild/BUILD/django-debreach-2.0.1/debreach/tests.py", line 85, in test_empty_response_body_ignored
[   42s]     middleware = RandomCommentMiddleware()
[   42s] TypeError: __init__() missing 1 required positional argument: 'get_response'
```

**Comment by lpomfrey** [comment]
This should all be addressed in the 2.1.0 release: https://github.com/lpomfrey/django-debreach/releases/tag/2.1.0
Let me know if there are any additional problems.

Thanks.
